# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTranscribe < Formula
  desc "A Go command-line tool that performs transcription using whisper.cpp."
  homepage ""
  version "1.1.0"
  license "MIT"
  depends_on :macos

  on_arm do
    url "https://github.com/kennyparsons/go-transcribe/releases/download/v1.1.0/go-transcribe_Darwin_arm64.tar.gz"
    sha256 "8cd3b646cbaa80fefd59cdefc508a52ac823fb13b8a5a4b291763820f2fb7efc"

    def install
      bin.install "go-transcribe"
      bin.install_symlink "go-transcribe" => "transcribe"
    end
  end

  test do
    system "#{bin}/go-transcribe --version"
  end
end
