# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTranscribe < Formula
  desc "A Go command-line tool that performs transcription using whisper.cpp."
  homepage ""
  version "1.6.1"
  license "MIT"

  depends_on "ffmpeg" => :formula
  depends_on :macos

  on_arm do
    url "https://github.com/kennyparsons/go-transcribe/releases/download/v1.6.1/go-transcribe_Darwin_arm64.tar.gz"
    sha256 "830bdb03eea6bd4f28d0f5935a93c4df8b9387d6ec70467bf97a7274227b5e90"

    def install
      bin.install "go-transcribe"
      bin.install_symlink "go-transcribe" => "transcribe"
    end
  end

  def caveats
    <<~EOS
      go-transcribe requires VLC to be installed. Please run 'brew install --cask vlc'.
    EOS
  end

  test do
    system "#{bin}/go-transcribe --version"
  end
end
