# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTranscribe < Formula
  desc "A Go command-line tool that performs transcription using whisper.cpp."
  homepage ""
  version "1.3.0"
  license "MIT"
  depends_on :macos

  on_arm do
    url "https://github.com/kennyparsons/go-transcribe/releases/download/v1.3.0/go-transcribe_Darwin_arm64.tar.gz"
    sha256 "124c1c5107bef7976378400914bda7400fc713dbacc02096fa8e1d28e7f201b6"

    def install
      bin.install "go-transcribe"
      bin.install_symlink "go-transcribe" => "transcribe"
    end
  end

  test do
    system "#{bin}/go-transcribe --version"
  end
end
